<a href="https://colab.research.google.com/github/kipsangchepesa/car_recognition_system/blob/main/Copy_of_uclan_mechatronic_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##importing libraries 

In [19]:
import pandas as pd 
import numpy as np
from google.colab import data_table
data_table.enable_dataframe_formatter()

installing scipy library for reading the .matlab file

In [7]:
pip install scipy

system vibration, speed response, stability, transmission response, power consumption,and shear stress

from scipy library import loadmat module to access loadmat function for loading the .matlab file 

In [8]:
from scipy.io import loadmat
#reading training dataset
url=(r"/content/training_dataset.mat")
data=loadmat(url)
x=data["b"]# b is the name of the matlab file 
print(x)

[[ 0.571281   -4.21358     2.97063    ... 10.20804702  6.15305755
   0.        ]
 [-0.430542    3.43296    -1.49606    ... 10.95824114  3.11805008
   0.        ]
 [ 4.49605    -2.3995      6.31082    ... 12.70424276  4.52824815
   0.        ]
 ...
 [-2.13224     4.04382     0.243046   ... 10.1010696   5.41634027
   1.        ]
 [-1.00359    -5.16748     7.661      ... 11.4287743   6.47149874
   1.        ]
 [-7.45809     4.79955    -0.0871139  ... 12.00124776  4.59288457
   0.        ]]


##converting the array to pandas dataframe 

and giving the column names that is 'system_vibration', 'speed_response', 'stability', 'transmission_response', 'power_consumption','shear_stress'and 'class'

In [20]:
training_data=pd.DataFrame(x, columns = ['system_vibration', 'speed_response',
                                         'stability', 'transmission_response', 
                                         'power_consumption','shear_stress','class'])
#np.set_printoptions(formatter={'float': '{:0.2f}'.format})

training_data

system_vibration  speed_response  ...  shear_stress  class
0             0.571281        -4.21358  ...      6.153058    0.0
1            -0.430542         3.43296  ...      3.118050    0.0
2             4.496050        -2.39950  ...      4.528248    0.0
3            -2.493180         5.75675  ...      6.358258    1.0
4            -1.609570        -3.80454  ...      5.610299    1.0
...                ...             ...  ...           ...    ...
3795          6.049790        -0.96180  ...      1.775637    0.0
3796          1.693530        -8.56853  ...      5.736646    1.0
3797         -2.132240         4.04382  ...      5.416340    1.0
3798         -1.003590        -5.16748  ...      6.471499    1.0
3799         -7.458090         4.79955  ...      4.592885    0.0

[3800 rows x 7 columns]

In [32]:
x=training_data.iloc[:, :-1].values
y=training_data.iloc[:, -1].values

In [22]:
#reading test dataset
url=(r"/content/test_dataset_no_GT.mat")
data=loadmat(url)
y=data["b_test_no_GT"]# b_test_no_GT is the name of the .matlab file 
print(y)


[[6.43 -2.77 -5.52 -4.91 10.80 5.47]
 [1.07 1.92 -0.65 3.20 10.59 5.47]
 [3.18 -3.58 -1.75 -9.46 10.25 7.66]
 ...
 [1.25 2.57 -1.22 3.56 11.32 6.05]
 [0.25 -0.55 -0.36 1.18 11.64 5.77]
 [3.85 3.26 -1.46 0.09 10.63 6.40]]


#converting the test dataset  to pandas dataframe

In [23]:
test_data = pd.DataFrame(y, columns = ['system_vibration', 'speed_response', 'stability', 'transmission_response', 'power_consumption','shear_stress'])

In [24]:
test_data

system_vibration  speed_response  ...  power_consumption  shear_stress
0            6.425990       -2.765910  ...          10.803924      5.465349
1            1.067190        1.915630  ...          10.587550      5.465797
2            3.175760       -3.576450  ...          10.254638      7.657937
3            5.866680       -3.874410  ...           9.653883      6.412760
4           -1.542440       -0.047196  ...          12.531339      5.515402
..                ...             ...  ...                ...           ...
195         -7.431220        1.184260  ...          11.671066      3.587439
196          3.299250       -3.192500  ...           8.918454      2.499965
197          1.248340        2.565860  ...          11.324682      6.049914
198          0.253283       -0.545857  ...          11.643680      5.772768
199          3.851280        3.260160  ...          10.630158      6.403699

[200 rows x 6 columns]

In [38]:
print(x.shape, y.shape)

(3800, 6) (3800,)


#Building a binary classification model using tensorflow

importing the librairies 

In [26]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [35]:
model=Sequential()
model.add(Dense(6, input_dim=len(x[0, :]), activation= "relu"))
model.add(Dense(3, activation= "relu"))
#sigmoid activation function is used here because its limit is o and 1 then its perfect for binary  classification
model.add(Dense(1, activation= "sigmoid"))


In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 42        
                                                                 
 dense_4 (Dense)             (None, 3)                 21        
                                                                 
 dense_5 (Dense)             (None, 1)                 4         
                                                                 
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


##building the model

In [37]:
model.compile(loss="binary_crossentropy", optimizer="rmsprop", metrics=['accuracy'])

#now training the model on the training dataset
model.fit(x,y, epochs=256, verbose=1)

Epoch 1/256
119/119 [==============================] - 1s 2ms/step - loss: 1.1567 - accuracy: 0.4647
Epoch 2/256
119/119 [==============================] - 0s 2ms/step - loss: 0.7834 - accuracy: 0.4866
Epoch 3/256
119/119 [==============================] - 0s 2ms/step - loss: 0.7005 - accuracy: 0.5158
Epoch 4/256
119/119 [==============================] - 0s 2ms/step - loss: 0.6872 - accuracy: 0.5279
Epoch 5/256
119/119 [==============================] - 0s 2ms/step - loss: 0.6831 - accuracy: 0.5397
Epoch 6/256
119/119 [==============================] - 0s 2ms/step - loss: 0.6798 - accuracy: 0.5500
Epoch 7/256
119/119 [==============================] - 0s 2ms/step - loss: 0.6768 - accuracy: 0.5653
Epoch 8/256
119/119 [==============================] - 0s 2ms/step - loss: 0.6743 - accuracy: 0.5705
Epoch 9/256
119/119 [==============================] - 0s 2ms/step - loss: 0.6720 - accuracy: 0.5779
Epoch 10/256
119/119 [==============================] - 0s 2ms/step - loss: 0.6691 - accura

##Doing prediction

In [39]:
prediction=model.predict(x)

In [40]:
#printing the first 10 prediction 
print(prediction[:10])

[[0.65]
 [0.00]
 [0.04]
 [0.69]
 [0.76]
 [0.62]
 [0.12]
 [0.17]
 [0.08]
 [0.51]]


In [41]:
#printing the truth class 
print(y[:10])

[0.00 0.00 0.00 1.00 1.00 1.00 0.00 0.00 0.00 1.00]


##Evaluating the model using the scikit learn library

In [42]:
#importing the standard metrics for evaluating the model

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

###evaluating using accuracy score 

In [45]:
my_accuracy= accuracy_score(y, prediction.round())
print(my_accuracy)

0.7747368421052632


The model accuracy is 77%

###evaluating using precision score

In [47]:
precision= precision_score(y,prediction.round())
print(precision)

0.7155243600330305


####Evaluating using recall score

In [49]:
recall=recall_score(y, prediction.round())
print(recall)

0.9121052631578948


It attained 91% percent accuracy

####Evaluating using f1 score

In [51]:
f1=f1_score(y,prediction.round())
print(f1)

0.8019435446552522


it attained 80% percent score 